name: Nightly Release

on:
  push:
    branches:
      - main

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Create tagname
        run: echo "tag_name=2.0.$(date +%s)" >> "$GITHUB_ENV"
      - name: Print tagname
        run: echo "created tag ${{ env.tag_name }}"
      - name: Nightly Release
        uses: Checkmarx/ast-jetbrains-plugin/.github/workflows/release.yml@main
        with:
          tag: ${{ env.tag_name }}
          rchannels: "nightly"
          secrets: inherit