name: Nightly Release

on:
  push:
    branches:
      - main

jobs:
  delete_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          delete_release: true
          tag_name: 2.0.0-SNAPSHOT
  nightly:
    needs: delete_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest prerelease tag
        id: latest_tag
        run: |
          git fetch --tags
          git tag --sort=-committerdate --points-at HEAD --merged 'refs/tags/*-*.*.*' --prerelease "*-*.*.*" | head -1 | xargs echo "::set-output name=tag::"
      - name: Increment version
        id: semver
        uses: anothrNick/github-tag-action@1.61.0
        with:
          github_token: ${{ secrets.TOKEN }}
          tag: ${{ steps.latest_tag.outputs.tag }}
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${{ steps.semver.outputs.new_tag }}" >> $GITHUB_ENV
      - name: Build
        run: ./gradlew buildPlugin
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.new_tag }}
          files: build/distributions/*
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin -Prchannels=nightly
