name: Nightly Release

on:
  push:
    branches:
      - main

jobs:
  show-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show latest pre-release
        id: prerelease
        run: |
          latest=$(git tag --list --sort=-v:refname "v*.*.*-*" | head -n1)
          echo "::set-output name=version::$latest"
      - name: Display output
        run: |
          echo "Latest pre-release version: ${{ steps.prerelease.outputs.version }}"
  delete_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          delete_release: true
          tag_name: 2.0.0-SNAPSHOT
  nightly:
    needs: delete_tag
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${{ steps.semver.outputs.new_tag }}" >> $GITHUB_ENV
      - name: Build
        run: ./gradlew buildPlugin
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.new_tag }}
          files: build/distributions/*
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin -Prchannels=nightly
