name: Nightly Release

on:
  push:
    branches:
      - main

jobs:
  delete_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: 2.0.0
  nightly:
    needs: delete_tag
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        run: |
          tag=$'2.0.'$(date +%s)
          echo "::set-env name=TAG_NAME::$tag"
      - name: Nightly Release
        uses: Checkmarx/ast-jetbrains-plugin/.github/workflows/release.yml@main
        with:
          tag: ${{ env.TAG_NAME }}
          rchannels: "nightly"
        secrets: inherit