name: Nightly Release

on:
  push:
    branches:
      - main

jobs:
  delete_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          delete_release: true
          tag_name: 2.0.0-SNAPSHOT
  set_tag:
    run: echo "tag_name=$'2.0.'$(date +%s) >> "$GITHUB_OUTPUT"
    id: tagname
  nightly:
    needs: delete_tag
    uses: Checkmarx/ast-jetbrains-plugin/.github/workflows/release.yml@main
    with:
      tag: ${{ jobs.tagname.outputs.tag_name }}"
      rchannels: "nightly"
    secrets: inherit